/* This file is automatically generated. DO NOT EDIT! */

#ifndef _funaux_h
#define _funaux_h


#define Id(v,i,j) v[(i)*(Nz)+(j)] 


typedef struct msr *MSR;


void sparserand (float *A, float densy, int Nx, int Nz, int a, int b);
/*< Sparse Matrix >*/


int formatMSR(float *A, int Nx, int Nz, MSR sparse);
/*< Sparse Matrix in MSR>*/

#endif
